### ISSUE TITLE
Implement Product Review Sentiment Dataset

### ISSUE THREAD

**Issue by onatyap** [GlobalMaksimum/sadedegel#219]
Previous datasets were rejected due to dataset size, I found a larger dataset in huggingface.
[turkish_product_reviews](https://huggingface.co/datasets/turkish_product_reviews)

This is not benchmarked but benchmarked datasets are hybrid which means they contain movie reviews, twitter posts and hotel reviews, which can be addressed as seperate datasets.

**Comment by husnusensoy** [comment]
Thanks for your recommendation. Here are two options for you

1. If there is already an academic work which we can bencmark ourselves please do refer to that one so that we can apply their method
2. Otherwise let's assume that this is a uniform dataset to see how well we perform over such a mixed copus ;)

In any way waiting for your baseline model

Regards,

**Comment by dafajon** [comment]
PR #226 is merged.
