### ISSUE TITLE
Control product_sentiment model after data patch

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#258]
product sentiment dataset is patched using human annotated subset of dataset. Please try to improve existing baseline classifier. 

Note that I have detected lots of inconsistencies in "human" annotated data!!!

**Comment by dafajon** [comment]
There is no improvement with the patched version after optimization. Current model is highest performing. Predictions are under error analysis. This branch is up to date with latest develop.

**Comment by husnusensoy** [comment]
Don't close issues without a documentation/detailed explanations ?!?!

**Comment by irmakyucel** [comment]
Closing this issue as: 

> There is no improvement with the patched version after optimization. Current model is highest performing. Predictions are under error analysis. This branch is up to date with latest develop.

Error analysis is done and errors as a result of wrong labelling and unknown tokens due to words with non-Turkish characters are found. The latter of the two can possibly be solved by word normalization. Word normalization is in development (issue #143).
 
Any improvements on the Product Review Sentiment model can be followed from issue #221.
