### ISSUE TITLE
Add tags filtering on summarizer evaluate

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#63]
Please discuss the behaviour of the click option here

**Comment by dafajon** [comment]
* To start with I will add `tag` parameter as a single option.
* Default tag will be `extractive` to get and test all summarizers.
* A list of tags should also be received, not just a single tag.
* Also tag names in the lowest level of tag hierarchy is still "grouped" such as `ml` that refers to multiple summarizers. I am planning to add unique tags to summarizers with their shorthand names ex: BandSummarizer -> `band`. So that users can test individual summarizers of their choice as well.
* There should be an exception if default word tokenizer is `simple`. `evaluate` should automatically filter out BERT dependent summarizers if that is the case.

**Comment by husnusensoy** [comment]
Please be more specific when you are in technical discussions.

`tag` click option should be of the form 

```python
@click.option('--tag', '-t', multiple=True)
```

So that you can add more than one tag for filtering. Default value of `extractive` is a great idea.

No need for 4 as a beginning
No need for 5 because it is not evaluation scripts job to check the tokenizer or so. Cluster based summarizer internally set the required tokenizer. Moreover note that there is no way to decide on tokenizer in evaluation. Completely irrelevant.

**Comment by dafajon** [comment]
Thanks for clarifications and comments.
