### ISSUE TITLE
Supervised Summarizer Training

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#90]
* `sadedegel-summarize` should have `train` command to start training process of a supervised ml model with (Embedding, Rouge1 Score) pairs.
* A `--dataset` option receiving dataset size as `mini` or `full`. 
* An `--embedding` option to pick from `bert` or other embedding type to come as feature enhancements. 
* Open to ideas about training API or its options without making it complicated. The aim is to provide user with simple training interface that can bu jumpstarted just by `sadedegel-summarize train --[OPTIONS] [ARGS]`

**Comment by husnusensoy** [comment]
Can you clearly state what model you will train using this commanline ? 

- What is your X ?
- What is your y ?

**Comment by dafajon** [comment]
* **`X:`** N-dim Sentence Embeddings
* **`y:`** Rouge1 Scores as Targets
* **Model:** Regressor to predict continuous Rouge1 targets. Initially a tree based ensemble.

**Comment by husnusensoy** [comment]
Ok thats fine. Here are a few things you should be careful

- [ ] Imitate sadedegel sentence boundary detectory in implementation so that

- [ ] You trained model predicting rouge1 can be serialized with sadedegel library (pickle or whatever)
- [ ] Retrain cli should be shipped (subcommand)
- [ ] Evaluation cli should be shipped (subcommand)

**Comment by dafajon** [comment]
Duplicate with all supervised summarizer issues. New issue as ranker summarizer will be opened.
